### ISSUE TITLE
getContextFromAddress() doesn't work

### ISSUE THREAD

**Issue by ghost** [simplegeo/Services_SimpleGeo#6]
getContextFromAddress("1 Market, San Francisco, CA") gives me a Services_SimpleGeo_Exception with a blank message. Looking carefully at the content of the exception and the API endpoint docs, it seems like the API requires the address to be quoted and urlencoded, but it is being passed without either.

Trying to work around this, getContextFromAddress("\"1+Market,+San+Francisco,+CA\"") gives me a Services_SimpleGeo_Exception with the message:

Invalid signature: expected base signature: GET&http%3A%2F%2Fapi.simplegeo.com%2F1.0%2Fcontext%2Faddress.json&address%3D%25221%2520Market%252C%2520San%2520Francisco%252C%2520CA%2522%26oauth_consumer_key%3DDKhqRNypNacwrefjWJSEsVYsmJMSG7V9%26oauth_nonce%3D6fb83810b6e8d11af7d3a6d574dc2db6%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1295556132%26oauth_version%3D1.0

I'm kind of stuck now, as it seems that some signing issue is happening somewhere along the line.

**Comment by shupp** [comment]
FWIW, I can't reproduce this problem.  This call works fine:

$result = $sgeo->getContextFromAddress('1 Market, San Francisco, CA');

It also works with other addresses I'm using.  I'm using the current source on github for Services_SimpleGeo.

**Comment by ghost** [comment]
You're right - it's been fixed since I noticed it in January. It looks like the fix was in getContextFromAddress (2ba9bf919e7b167d7574d35a386a77e51a9e8036) - it now passes 'address' to the OAuth consumer in the args array, rather than by putting it in a query string appended to the endpoint.
